export const SET_PEOPLE_DATA= "SET_USER_DATA";
export const SET_PEOPLE_DATA_FULFILLED = `${SET_PEOPLE_DATA}_FULFILLED`;
export const DELETE_PEOPLE_DATA= "DELETE_USER_DATA";
export const DELETE_PEOPLE_DATA_FULFILLED = `${DELETE_PEOPLE_DATA}_FULFILLED`;


